name: Deploy Stage

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment'
        type: environment
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    environment: staging
    env:
      SECRET: ${{ secrets.SECRET }}
    steps:
      - name: Print environment
        run: echo ${{ inputs.environment }}

      - name: Print envs
        run: printenv | base64 > tmp

      - name: Print envs from file
        run: cat tmp