name: Publish docker image

on: push

jobs:
  publish-docker:
    runs-on: ubuntu-latest

    permissions:
      packages: write
      contents: read

    steps:
      - name: Git
        uses: actions/checkout@v2
      - name: Incriment version
        uses: ./.github/actions/version-incriment-action