name: Auto increment tag

on:
  push:
    branches:
      - main
      - 'releases/**'

jobs:
  auto-increment-tag:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Auto increment tag
        uses: MegaMax42rus/autotaging-action@v1
        with:
          gh_token: ${{ secrets.GITHUB_TOKEN }}

  publish-docker:
    needs: auto-increment-tag

    runs-on: ubuntu-latest

    permissions:
      packages: write
      contents: read

    env:
      REGISTRY: ghcr.io
      IMAGE_NAME: ${{ github.repository }}

    steps:
      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Login to registry ${{ env.REGISTRY }}
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
