name: Auto increment tag

on:
  pull_request:
  push:
    branches:
      - master
      - 'release/**'
  workflow_dispatch:

jobs:
  auto-increment-tag:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Test action
        uses: MegaMax42rus/test-action@main
        with:
          gh_token: ${{ secrets.GITHUB_TOKEN }}
