name: Publish docker image

on: push

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  publish-docker:
    runs-on: ubuntu-latest

    permissions: write-all
#      packages: write
#      contents: read

    steps:
      - name: Git
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Incriment version
        id: version
        uses: ./.github/actions/version-incriment-action

      - name: Log into registry ${{ env.REGISTRY }}
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ lowercase(env.REGISTRY) }}/${{ env.IMAGE_NAME }}:${{ steps.version.outputs.tag }}
          labels: ${{ steps.meta.outputs.labels }}

          #pushing ghcr.io/megamax42rus/my-action-sandbox:master with docker
