name: Auto increment tag

on:
  push:
    workflow_dispatch:
    branches:
      - master
      - 'release/**'

jobs:
  auto-increment-tag:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Test action
        uses: MegaMax42rus/test-action@develop
        with:
          gh_token: ${{ secrets.GITHUB_TOKEN }}
