name: Auto increment tag

on:
  push:
    branches:
      - main
      - 'releases/**'

jobs:
  auto-increment-tag:
    name: Auto increment tag
    runs-on: ubuntu-latest

    steps:
      - name: Auto increment tag
        uses: MegaMax42rus/autotaging-action@v1
        with:
          gh_token: ${{ secrets.PAT }}
