name: Auto increment tag

on:
  push:
    branches:
      - main
      - 'releases/**'

jobs:
  auto-increment-tag:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Auto increment tag
        uses: MegaMax42rus/autotaging-action@v1
        with:
          gh_token: ${{ secrets.GITHUB_TOKEN }}

  publish-docker:
    needs: auto-increment-tag

    runs-on: ubuntu-latest

    permissions:
      packages: write
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        ref: main

      - name: Publish Docker image
        uses: ./.github/workflows/publish-docker-image.yaml
