name: Deploy Stage

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Print envs
        run: printenv > tmp

      - name: Print envs from file
        run: cat tmp