name: Deployment

on:
  push:
    branches:
      - 'main'
      - 'production'
      - 'staging'
      - 'development'
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deployment'
        required: true
        default: ${{ github.base_ref }}
        type: environment

jobs:
  deployment:
    name: Deployment
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}

    steps:
      - name: Print environments
        run: 'printenv'
